### ISSUE TITLE
predict的一些问题

### ISSUE THREAD

**Issue by MrAccelerator** [zhangbaijin/SpA-Former-shadow-removal#10]
你好，我试了一下predict跑了一张图片，但是跑出来的效果很差，我用的是gen_model_epoch_160.pth 然后config里面都是默认的。
原图
![图片](https://user-images.githubusercontent.com/56375036/208854596-531b793e-c7f9-45bd-b90a-70577a4ef0e4.png)
预测图
![图片](https://user-images.githubusercontent.com/56375036/208854672-f6defd13-de85-4067-adb6-c9b95ce5af5b.png)
我的图片大小都是640x480，但是我看数据加载的时候加载出来是(3,480,640)，而且config里面设置的是宽480高640？这里是不是有问题啊

**Comment by MrAccelerator** [comment]
![图片](https://user-images.githubusercontent.com/56375036/208855751-a3ce4e28-1db1-4c0c-9241-b2c76a816543.png)

**Comment by zhangbaijin** [comment]
是的，一些图的效果确实是有待提升，我的建议是你把图片用256X256或者512X512进行训练测试，效果是提升的，已经验证过。epoch250效果最佳，因为之前时间问题，没有把最新的checkpoint传上去。
