### ISSUE TITLE
关于train和val的问题

### ISSUE THREAD

**Issue by MrAccelerator** [zhangbaijin/SpA-Former-shadow-removal#11]
我看在eval.py中对比生成图像和目标图像的相似度时，生成图和目标图有个
img1 = np.tensordot(out.cpu().numpy()[0, :3].transpose(1, 2, 0), [0.298912, 0.586611, 0.114478], axes=1)
img2 = np.tensordot(t.cpu().numpy()[0, :3].transpose(1, 2, 0), [0.298912, 0.586611, 0.114478], axes=1)
操作，这个操作是干什么的呀？[0.298912, 0.586611, 0.114478],这个数据又是什么作用？
还有我看训练的时候还用到了Discriminator，但是我看论文中没有提到，想问一下这个的作用。
然后想问一下arXiv上论文还会不会更新呀

**Comment by zhangbaijin** [comment]
这个操作是在通道的维度上计算点积。这个数据的作用可以看作是一个阈值。这篇文章就是GAN加上一些编码解码层，后续论文不会再更新，谢谢关注~

**Comment by laoxie521** [comment]
那个数组值可以改变吗，我用自己的数据集训练，出错在这里，我怀疑是数组的范围不对，这个范围怎么求呢
