### ISSUE TITLE
Is training dataset required to be paired (i.e. supervised learning)?

### ISSUE THREAD

**Issue by pengzhao-life** [zhangbaijin/SpA-Former-shadow-removal#12]
Hi, thanks for sharing the great work! I wonder if I want to finetune the model with my own dataset. My training dataset needs to be paired? i.e., each pair is a shadow image and its corresponding shadow-free image? Can the training dataset be unpaired?

Thanks!

**Comment by zhangbaijin** [comment]
Hi, thansk for your  attention, yes, the training dataset must be paired(input/ground truth), is unbale to be trained unpaired.

**Comment by pengzhao-life** [comment]
Thanks for the response and explanation!
