### ISSUE TITLE
 SSIM  data_range

### ISSUE THREAD

**Issue by wangchenxixixi** [zhangbaijin/SpA-Former-shadow-removal#14]
File "/usr/local/lib/python3.8/dist-packages/skimage/metrics/_structural_similarity.py", line 194, in structural_similarity
raise ValueError(
ValueError: Since image dtype is floating point, you must specify the data_range parameter. Please read the documentation carefully (including the note). It is recommended that you always specify the data_range anyway. 作者您好 我用SSIM这个缺少一个data_range参数 按照您给的640 480 像素 这个参数值应该是写多少呢

**Comment by zhangbaijin** [comment]
这个是scikit-image的版本问题，可以降版本或者升级版本一下
