### ISSUE TITLE
gpu 编号问题

### ISSUE THREAD

**Issue by wuzhiqi111** [zhangbaijin/SpA-Former-shadow-removal#16]
你好，使用除了0号卡训练，包括单卡和多卡好像都有问题，比如说，我规定了卡[2,3]，但是仍然显示卡是[1,2]。后来我把这个解决了。。。。

问题仍然没有解决，仍然报错。即使我将卡规定在了[2,3]，仍然说有部分数据放在了0上面跑。
![b150599416e80ce355afc59e8a72637](https://github.com/zhangbaijin/SpA-Former-shadow-removal/assets/70802864/b51e550e-e936-432d-a8e4-c683860dc222)
![a402c63c603024f64184b455ac61926](https://github.com/zhangbaijin/SpA-Former-shadow-removal/assets/70802864/bac90e42-d29b-4d07-90ac-0a84f433dd28)

**Comment by zhangbaijin** [comment]
因为在config.yaml里面默认了gpu_ids: [0]，得从里面改

**Comment by wuzhiqi111** [comment]
改过了 改成2，3 了

![image](https://github.com/zhangbaijin/SpA-Former-shadow-removal/assets/70802864/2a1effcd-0ccd-4f35-b46f-e62dbaf81de0)
这里的思路是什么 直接默认进了0还是什么

**Comment by zhangbaijin** [comment]
好像是直接默认进0了，没有多GPU训练过（哭笑），一般单GPU也够了呀

**Comment by wuzhiqi111** [comment]
qaq,好吧。 因为0，1被人占掉了 所以想换其他的来训。 我们的图象是1920x1440的，单卡40g够吗

**Comment by zhangbaijin** [comment]
估计悬，输入太大了，不过可以试试

**Comment by wuzhiqi111** [comment]
我们采用了随机裁剪的方法，在traindataset里面加了几行cropping的代码。

另外，有一个关于ssim计算的错误，在归一化之后要填上data_range，否则会报错。

![image](https://github.com/zhangbaijin/SpA-Former-shadow-removal/assets/70802864/2af42f3e-e03d-4c20-8e2b-f8516cc961ce)
