### ISSUE TITLE
predict.py issue

### ISSUE THREAD

**Issue by SEONGMIN-96** [zhangbaijin/SpA-Former-shadow-removal#3]
```
Traceback (most recent call last):
  File "predict.py", line 84, in <module>
    predict(config, args)
  File "predict.py", line 58, in predict
    allim[0, 2, :] = heat_att
IndexError: index 2 is out of bounds for axis 1 with size 1
```

This error occurred and ignored code 'allim[0, 2, :] = heat_att' and executed successfully.
Is there any problem with the performance of the model?

**Comment by zhangbaijin** [comment]
I upload the predict.py again, try it. It should be no problem.

**Comment by zhangbaijin** [comment]
你的测试图片输入对吗，你的这个问题跟第一个issue差不多，可以参考 #2
