### ISSUE TITLE
Predict.py not working ,  untitled1 not found

### ISSUE THREAD

**Issue by noshluk2** [zhangbaijin/SpA-Former-shadow-removal#4]
ModuleNotFoundError: No module named 'untitled1'

**Comment by zhangbaijin** [comment]
Please download the full code again, I updata the project. Thanks

**Comment by Andy-YX** [comment]
> Please download the full code again, I updata the project. Thanks

Hello, awesome work! However, from what I can see, the #13 line of predict.py is still 'from untitled1 import Generator'.

And also, in Predict.py,
'h = 1
w = 1
c = 3
p = config.width
q = config.height
...
allim[0, 0, :] = in_rgb * 255
allim[0, 0, :] = out_rgb * 255
allim[0, 2, :] = heat_att',
of which the last line 'allim[0, 2, :] = heat_att' still cause errors.

Could you please point out where you update the codes?

Thanks!

**Comment by Andy-YX** [comment]
> > Please download the full code again, I updata the project. Thanks
> 
> Hello, awesome work! However, from what I can see, the #13 line of predict.py is still 'from untitled1 import Generator'.
> 
> And also, in Predict.py, 'h = 1 w = 1 c = 3 p = config.width q = config.height ... allim[0, 0, :] = in_rgb * 255 allim[0, 0, :] = out_rgb * 255 allim[0, 2, :] = heat_att', of which the last line 'allim[0, 2, :] = heat_att' still cause errors.
> 
> Could you please point out where you update the codes?
> 
> Thanks!

Never mind, I have figured out the typos. Thanks!

**Comment by zhangbaijin** [comment]
Best wishes!

**Comment by noshluk2** [comment]
Solved it by replacing  manually line 13 in predict.py with

**from SpA_Former import Generator**

**Comment by noshluk2** [comment]
> > > Please download the full code again, I updata the project. Thanks
> > 
> > 
> > Hello, awesome work! However, from what I can see, the #13 line of predict.py is still 'from untitled1 import Generator'.
> > And also, in Predict.py, 'h = 1 w = 1 c = 3 p = config.width q = config.height ... allim[0, 0, :] = in_rgb * 255 allim[0, 0, :] = out_rgb * 255 allim[0, 2, :] = heat_att', of which the last line 'allim[0, 2, :] = heat_att' still cause errors.
> > Could you please point out where you update the codes?
> > Thanks!
> 
> Never mind, I have figured out the typos. Thanks!

Can you please share those typos ? i cannot solve it .

**Comment by Andy-YX** [comment]
> > > > Please download the full code again, I updata the project. Thanks
> > > 
> > > 
> > > Hello, awesome work! However, from what I can see, the #13 line of predict.py is still 'from untitled1 import Generator'.
> > > And also, in Predict.py, 'h = 1 w = 1 c = 3 p = config.width q = config.height ... allim[0, 0, :] = in_rgb * 255 allim[0, 0, :] = out_rgb * 255 allim[0, 2, :] = heat_att', of which the last line 'allim[0, 2, :] = heat_att' still cause errors.
> > > Could you please point out where you update the codes?
> > > Thanks!
> > 
> > 
> > Never mind, I have figured out the typos. Thanks!
> 
> Can you please share those typos ? i cannot solve it .

Hello, 

you may try
w = 1 -> w = **3**
allim[0, 0, :] = out_rgb * 255 -> allim[0, **1**, :] = out_rgb * 255
