### ISSUE TITLE
configuration and memory?

### ISSUE THREAD

**Issue by LiliiiH** [zhangbaijin/SpA-Former-shadow-removal#5]
Thanks for your great work! But I can't find any instructions for configuration, can you tell me how to set up the environment in order to run predict.py. Thanks!

**Comment by zhangbaijin** [comment]
python3.7-3.8 pytorch1.4-1.8. It's ok

**Comment by LiliiiH** [comment]
Thank you so much!

**Comment by LiliiiH** [comment]
I met this error when I wanted to run train.py:
RuntimeError: CUDA out of memory. Tried to allocate 400.00 MiB (GPU 0; 24.00 GiB total capacity; 18.64 GiB already allocated; 2.32 GiB free; 19.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Can you tell me how to solve it? Is 'setting max_split_size_mb' the only way to solve?
Thanks for your patience!

**Comment by zhangbaijin** [comment]
Sorry for late to reply you, have you solved the Our of memory problem?

**Comment by HumeraSabir** [comment]
I am facing the same, "CUDA out of memory" issue, 
Is there any solution

**Comment by Mnurr** [comment]
I am facing the same, "CUDA out of memory" issue,

**Comment by zhangbaijin** [comment]
我是在单张3090训练和推理的，我建议你们可以通过big_resize.py将输入变为256x256，这样应该不会报out of memory的错误

**Comment by ShunTatsukawa** [comment]
By lowering the batch size and changing the input image size to 256x256, I was able to train on a 3060ti with 8GB memory.👍👍

**Comment by zhangbaijin** [comment]
It's really happy to help you, if you have any questions, please email me.
