### ISSUE TITLE
TRAINING ISSUE

### ISSUE THREAD

**Issue by Hamzat0014** [zhangbaijin/SpA-Former-shadow-removal#7]
I am trying to train on ISTD dataset and facing the following error. All the images in train, test dataset are of 640x480.
The error arises after 1 epoch. 

Traceback (most recent call last):
  File "train.py", line 184, in <module>
    train(config)
  File "train.py", line 159, in train
    log_validation = test(config, validation_data_loader, gen, criterionMSE, epoch)
  File "/content/drive/MyDrive/THESISMODELS/SpA/SpA-Former-shadow-removal/eval.py", line 49, in test
    allim[0, 0, :] = in_rgb * 255
ValueError: could not broadcast input array from shape (3,640,480) into shape (3,256,256)

**Comment by zhangbaijin** [comment]
Did you set the wrong parameter in config.yaml?

**Comment by zhangbaijin** [comment]
Or you can see if there are any stranded files like ipycheckoints in the dataset, delete them

**Comment by Hamzat0014** [comment]
> Did you set the wrong parameter in config.yaml?

I have set the batch_size = 1 instead of 4 because of GPU Memory constraint.

**Comment by Hamzat0014** [comment]
> Or you can see if there are any stranded files like ipycheckoints in the dataset, delete them

i can only see "val_list.txt" file in test folder and "train_list.txt" in train folder.

**Comment by Hamzat0014** [comment]
Referring to your readme, you have said "First，the dataset is trained on 640x480, so you should resize test dataset to 640X480, you can use the code to resize your image bash python bigresize.py and then follow the code to test the results"

According to this the test data must be 640x480, and you have given the script "bigresize.py" to resize the test dataset, but the the provided script resize the images to 256x256, please confirm either have to resize the images to 256x256 or 640x480.

**Comment by zhangbaijin** [comment]
please check your dataset is 640X480? is there any incorrect file in your val_list.txt and train_list.txt

**Comment by Hamzat0014** [comment]
can you please share your training dataset?

**Comment by Hamzat0014** [comment]
Thanks for your kind response. I have figured out the error.

The error was in "eval.py" in line 49,50 and 51. There was a mismatching in the "allim" shape. The model is on training now.

            allim[0, 0, :] = in_rgb * 255
            allim[0, 1, :] = out_rgb * 255
            allim[0, 2, :] = t_rgb * 255

**Comment by zhangbaijin** [comment]
ok, best wishes
