### ISSUE TITLE
Mis-Match Results

### ISSUE THREAD

**Issue by Hamzat0014** [zhangbaijin/SpA-Former-shadow-removal#8]
Hello Brother,
Thanks for the amazing work. 

I have done inference of ISTD test data set images with the the checkpoint provided by you. I am unable to get the good results.
The model is performing extremally well when there is a "grey" color image at its input.
![95-4](https://user-images.githubusercontent.com/95419825/193249625-f7bd10fe-7727-4afa-9f0b-219da63d2691.png)

But when there is a combination of colors i.e. even 2 colors in an image, there is hardly any difference between the input image and the output shadow image produced. Few of the results are attached.
![90-1](https://user-images.githubusercontent.com/95419825/193249538-1374bc0a-1952-433f-b8c3-734a229838c2.png)
![91-1](https://user-images.githubusercontent.com/95419825/193249586-90681b95-2f74-4344-a292-bdf0db9d0fb3.png)
![96-6](https://user-images.githubusercontent.com/95419825/193249661-75c8c6be-886c-433e-9bbc-38c6097f7b78.png)

**Comment by zhangbaijin** [comment]
yeah,there is a problem haven't been solved, I think the ISTD dataset has a large variety of scenes, and there are not so many scene samples. I suggest that you can train on ISTD+ or improve the number of samples through data enhancement
