### ISSUE TITLE
Why use bg-shadow instead of Mask file provided by ISTD?

### ISSUE THREAD

**Issue by cy810557** [zhangbaijin/SpA-Former-shadow-removal#9]
Hi, 
    I noticed that the original train_B folder is not used, and TrainDataset simply returns "np.clip((t-x).sum(axis=2), 0, 1)" as shadow mask(or matte).  Does this rough mask perform better than original mask, or are there other reasons for using this setting? As it's a known issue that a part of images in ISTD have highly non-consistent lightness between bg & shadow.

**Comment by zhangbaijin** [comment]
在训练中并没有使用mask,训练过程是单阶段Image-attention-deshadowed image,且在最开始的ISTD是没有mask的，是后面学者生成的。本文的初衷是一种简单而快速的去阴影网络
